server:
  port: ${SERVER_PORT:9005}
spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:ow_orders_db}
kafka:
  bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
  topic-name: ${KAFKA_TOPIC:customer_orders}