kind: Deployment
apiVersion: apps/v1
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: nkrishnakumar/bk-istio-order-service:#{Build.BuildId}#
          imagePullPolicy: Always
          ports:
            - containerPort: 9005
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: organic-world-config
                  key: mongo-host
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: organic-world-config
                  key: mongo-port
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: organic-world-config
                  key: mongo-database
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: organic-world-config
                  key: kafka-host
            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: organic-world-config
                  key: kafka-topic
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: organic-world-config
                  key: kafka-topic
            - name: EUREKA_URL
              valueFrom:
                configMapKeyRef:
                  name: organic-world-config
                  key: eureka-url
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: organic-world-config
                  key: config-server-url
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9005
            initialDelaySeconds: 45
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9005
            initialDelaySeconds: 45
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  type: NodePort
  ports:
    - port: 9005
      targetPort: 9005
      protocol: TCP
      nodePort: 32002
      name: order-service
  selector:
    app: order-service